package vn.heomc.livingnpc;

enum PlacementType {
    CREATE_RESIDENT,
    SET_HOME,
    SET_PLOT,
    SET_TOWN_STORAGE,
    SET_WORK_ZONE,
    SET_RANCH_PEN,
    SET_MINING_ZONE,
    SET_MARKET_POINT,
    SET_SCENIC_POINT,
    SET_VISITOR_GATE,
    SET_SEAT,
    SET_MERCHANT_SELLER,
    SET_MERCHANT_BUYER
}
